name: ontheweekends
favicon: null
layout_spectrum: 0.7443386670202017
typography_spectrum: 0.2236289270222187
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.371106187812984
  lightness: 0.05845273635350168
  saturation: 0.9988333575893193
  rhythmicContrast: 0.546855885302648
purpose: []
